name: CI
on: push

jobs:
    posix-build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest]
        steps:
        - uses: actions/checkout@v2
        - name: Install Dependencies
          run: vcpkg install catch2
        - name: Build Debug
          run: ./build.sh
        - name: Build Release
          run: ./buildRelease.sh
        - name: Build Docker Debug
          run: ./buildDocker.sh
        - name: Build Docker Release
          run: ./buildDockerRelease.sh
        - name: Upload Code Coverage.
          run: |
            cd build
            ctest -j9
            bash <(curl -s https://codecov.io/bash)
                -t ${{ secrets.CODECOV_TOKEN }}
    windows-build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@v2
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Install Dependencies
        run:  vcpkg install catch2
      - name: Build Debug
        run: |
          cmake --config=Debug .
          msbuild PaperTrader.sln
      - name: Build Release
        run: |
          cmake --config=Release .
          msbuild PaperTrader.sln
